### ISSUE TITLE
crudapi这个项目代码，和 example中引用的，不一致

### ISSUE THREAD

**Issue by mengshuai85** [crudapi/crudapi#1]

**Comment by crudapi** [comment]
## GIT地址
名称 | 类型 | 授权 | GitHub仓库 | Gitee仓库
--- | --- | --- | --- | ---
crudapi-admin-web | Vue Qusar源码 | 开源 | [crudapi-admin-web](https://github.com/crudapi/crudapi-admin-web) | [crudapi-admin-web](https://gitee.com/crudapi/crudapi-admin-web)
crudapi-example| Java集成SDK | 永久免费 | [crudapi-example](https://github.com/crudapi/crudapi-example) | [crudapi-example](https://gitee.com/crudapi/crudapi-example)
crudapi| Java源码(开源中...) | 开源 | [crudapi](https://github.com/crudapi/crudapi) | [crudapi](https://gitee.com/crudapi/crudapi)

备注：
1. 目前后台Java代码[crudapi](https://github.com/crudapi/crudapi)正在重构中，持续更新。
2. 在重构完成之前，请先使用[crudapi-example](https://github.com/crudapi/crudapi-example)，通过SDK集成，功能无任何限制。
3. 如需提前下载crudapi后台Java源码，请微信联系。

### 文档
[https://help.crudapi.cn](https://help.crudapi.cn)

1. [基于Java和Spring Boot的后端零代码crudapi项目实战之环境搭建（一）](https://help.crudapi.cn/crudapi/helloworld.html)

持续更新中。。。
